/*
O arquivo `app/layout.tsx` é o layout raiz da aplicação. 
Ele envolve todas as páginas e componentes, permitindo definir estilos globais, fontes e provedores de contexto que estarão disponíveis em toda a aplicação.
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CounterProvider } from "@/context/global-counter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
